name: synprefenv
channels:
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.4.0
  - cudatoolkit=10.1
  - absl-py
  - pyparsing
  - pip
  - pip:
    - termcolor
    - dm_control
    - tb-nightly
    - imageio
    - imageio-ffmpeg
    - git+https://github.com/facebookresearch/hydra@0.11_branch
    - matplotlib
    - glfw==1.11.2
    - scikit-image
    - accelerate
    - einops
    - ema-pytorch
    - tqdm
