defaults:
    - agent: sac

# this needs to be specified manually
experiment: PEBBLEwSyn


# diffusion model
# SAC/REDQ diffusion args.
retrain_diffusion_every: 10000
diffusion_sample_ratio: 0.5
skip_reward_norm: True

normalizer_type: 'standard'

model_terminals: False  # No terminals in DMC(False), OpenAI(True)
num_samples: 200000
print_buffer_stats: true
diffusion_start: 0
diffusion_schedule: false

# Diffusion training.
train_batch_size: 256
train_lr: 3e-4
lr_scheduler: "cosine"
weight_decay: 0
train_num_steps: 100000
# Don't save.
save_and_sample_every: 100000000

# Diffusion denoising network.
dim_t: 256
mlp_width: 1024
num_layers: 6
learned_sinusoidal_cond: False
random_fourier_features: True
learned_sinusoidal_dim: 16
diff_activation: 'relu'
layer_norm: False

# Diffusion sampling.
num_sample_steps: 128


# reward learning
segment: 50
activation: tanh
num_seed_steps: 1000
num_unsup_steps: 5000
num_interact: 5000
reward_lr: 0.0003
reward_batch: 128
reward_update: 200
feed_type: 0
reset_update: 100
topK: 5
ensemble_size: 3
max_feedback: 1400
large_batch: 10
label_margin: 0.0
teacher_beta: -1
teacher_gamma: 1
teacher_eps_mistake: 0
teacher_eps_skip: 0
teacher_eps_equal: 0

# scheduling
reward_schedule: 0

num_train_steps: 1e6
replay_buffer_capacity: ${num_train_steps}

# evaluation config
eval_frequency: 10000
num_eval_episodes: 10
device: cuda

# logger
log_frequency: 10000
log_save_tb: true

# video recorder
save_video: false

# setups
seed: 1

# Environment
env: dog_stand
gradient_update: 1

positive_weight: 0.1
negative_weight: 0.1


# hydra configuration
hydra:
    name: ${env}
    run:
        dir: ./exp/${env}/Highl_S${retrain_diffusion_every}_H${diag_gaussian_actor.params.hidden_dim}_L${diag_gaussian_actor.params.hidden_depth}_lr${agent.params.actor_lr}/teacher_b${teacher_beta}_g${teacher_gamma}_m${teacher_eps_mistake}_s${teacher_eps_skip}_e${teacher_eps_equal}/label_smooth_${label_margin}/schedule_${reward_schedule}/${experiment}_init${num_seed_steps}_unsup${num_unsup_steps}_inter${num_interact}_maxfeed${max_feedback}_seg${segment}_act${activation}_Rlr${reward_lr}_Rbatch${reward_batch}_Rupdate${reward_update}_en${ensemble_size}_sample${feed_type}_large_batch${large_batch}_seed${seed}